[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "cd ~/Downloads"
desc = "Go ~/Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Projects"
desc = "Go ~/Projects"

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = "cd ~/Temporary"
desc = "Go ~/Temporary"

[[mgr.prepend_keymap]]
on   = [ "g", "k" ]
run  = "cd ~/Desktop"
desc = "Go ~/Desktop"

[[mgr.prepend_keymap]]
on   = [ "g", "v" ]
run  = "cd ~/Development"
desc = "Go ~/Development"

[[mgr.prepend_keymap]]
on   = "e"
run  = "shell --block -- extract %s"
desc = "Extract archive(s)"

[[mgr.prepend_keymap]]
on   = "<C-t>"
run  = "shell --block -- tlp -t %s"
desc = "tlp: push selection to remote"

