[opener]
edit = [
  { run = "$EDITOR %s", block = true, for = "unix" },
]

browser = [
  { run = 'open -a "Firefox" %s', orphan = true, desc = "Open in Firefox", for = "macos" },
  { run = "xdg-open %s",          orphan = true, desc = "Open in browser", for = "linux" },
]

preview = [
  { run = 'open -a "Preview" %s', orphan = true, desc = "Open in Preview", for = "macos" },
]

rstudio = [
  { run = 'open -a "RStudio" %s', orphan = true, desc = "Open in RStudio", for = "macos" }
]

inkscape = [
  { run = 'open -a "inkscape" %s', orphan = true, desc = "Open in Inkscape", for = "macos" }
]

extract = [
  { run = "extract %s", block = true, desc = "Extract here" },
]

[open]
prepend_rules = [
  { url = "*.r",    use = [ "edit",    "rstudio" ] },
  { url = "*.html", use = [ "browser", "edit"    ] },
  { url = "*.htm",  use = [ "browser", "edit"    ] },
  { url = "*.gif",  use = [ "browser", "preview" ] },
  { url = "*.svg",  use = [ "inkscape", "edit", "browser" ] },

  { url = "*.zip",     use = "extract" },
  { url = "*.tar",     use = "extract" },
  { url = "*.tar.gz",  use = "extract" },
  { url = "*.tgz",     use = "extract" },
  { url = "*.tar.bz2", use = "extract" },
  { url = "*.tbz2",    use = "extract" },
  { url = "*.tar.xz",  use = "extract" },
  { url = "*.txz",     use = "extract" },
  { url = "*.tar.zst", use = "extract" },
  { url = "*.7z",      use = "extract" },
  { url = "*.rar",     use = "extract" },
  { url = "*.gz",      use = "extract" },
  { url = "*.bz2",     use = "extract" },
  { url = "*.xz",      use = "extract" },
  { url = "*.zst",     use = "extract" },
]
